name: Commands Workflow

on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if a file exists
        run: |
          if [ -f "README.md" ]; then
            echo "::debug::README.md exists"
          else
            echo "::error::README.md is missing"
          fi
